version: '3.5'
services:
  gitlab-runner:
    build: ./
    container_name: gitlab-runner-unity
    restart: unless-stopped
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./unity/Editor:/mnt/hd1/unity/Editor
